global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'oci-sd'
    scrape_interval: 5s
    file_sd_configs:
    - files:
      - oci-sd.json
      refresh_interval: 1m
    relabel_configs:
    - source_labels: ['__meta_oci_public_ip']
      target_label: '__address__'
      replacement: '${1}:9100'
    - source_labels: ['__meta_oci_instance_id']
      target_label: 'instance_id'
    - source_labels: ['__meta_oci_instance_name']
      target_label: 'instance_name'
    - source_labels: ['__meta_oci_instance_state']
      target_label: 'instance_state'
    - source_labels: ['__meta_oci_freeform_tag_prometheus_exporter']
      target_label: 'prometheus_exporter'
    - source_labels: ['__meta_oci_freeform_tag_prometheus_exporter']
      regex: 'node_exporter'
      action: 'keep'
